spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/backenddb
        username: sa
        password: sa
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: 'create-drop'

security:
    jwt:
        token:
            secret-key: 1234abc
